/** Extra copy/specs for product detail UI (per product id). */

export type SpecCell = { label: string; value: string };

export type ProductDetailExtra = {
  sku: string;
  /** 3×3 grid order (9 items) */
  grid: SpecCell[];
  /** Key/value list (same data, list layout) */
  list: SpecCell[];
  /** Long marketing paragraph under tabs */
  longIntro: string;
  manualFileLabel: string;
};

export const productDetailExtras: Record<string, ProductDetailExtra> = {
  "tv-50-4k-uhd": {
    sku: "HYLED-50UHD7A",
    grid: [
      { label: "Brand", value: "HYUNDAI" },
      { label: "Model", value: "HYLED-50UHD7A" },
      { label: "Screen size", value: '50"' },
      { label: "Resolution", value: "4K UHD 3840 × 2160" },
      { label: "Operating system", value: "Android R" },
      { label: "Wi‑Fi", value: "Yes" },
      { label: "HDMI", value: "As marked on unit" },
      { label: "USB", value: "As marked on unit" },
      { label: "Dimensions (approx.)", value: "1120 × 650 × 76 mm" },
      { label: "Audio", value: "Dolby Digital Plus 10W × 2" },
      { label: "Color", value: "BLACK" },
      { label: "Warranty", value: "1 year" },
    ],
    list: [
      { label: "Brand", value: "HYUNDAI" },
      { label: "Model", value: "HYLED-50UHD7A" },
      { label: "Screen size", value: '50"' },
      { label: "Resolution", value: "4K UHD 3840 × 2160" },
      { label: "Operating system", value: "Android R" },
      { label: "Wi‑Fi", value: "Yes" },
      { label: "HDMI", value: "As marked on unit" },
      { label: "USB", value: "As marked on unit" },
      { label: "Dimensions (approx.)", value: "1120 × 650 × 76 mm" },
      { label: "Audio", value: "Dolby Digital Plus 10W × 2" },
      { label: "Color", value: "BLACK" },
      { label: "Warranty", value: "1 year" },
    ],
    longIntro:
      "The Hyundai HYLED-50UHD7A combines advanced technology with stunning 4K UHD resolution so you can enjoy every detail. Perfect for your home, it features Wi‑Fi connectivity, an Android operating system, and excellent color reproduction for an immersive viewing experience.",
    manualFileLabel: "Download PDF (2.1 MB)",
  },
  "tv-58-4k-uhd": {
    sku: "HYLED-58UHD7A",
    grid: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HYLED-58UHD7A" },
      { label: "Screen size", value: '58"' },
      { label: "Resolution", value: "4K UHD 3840 × 2160" },
      { label: "Operating system", value: "Android R" },
      { label: "Wi‑Fi", value: "Yes" },
      { label: "HDMI", value: "3 ports" },
      { label: "USB", value: "2 ports" },
      { label: "Dimensions (approx., with stand)", value: "1295 × 750 × 80 mm" },
      { label: "Audio", value: "Dolby Digital Plus 10W × 2" },
      { label: "Color", value: "BLACK" },
      { label: "Warranty", value: "1 year" },
    ],
    list: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HYLED-58UHD7A" },
      { label: "Screen size", value: '58"' },
      { label: "Resolution", value: "4K UHD 3840 × 2160" },
      { label: "Operating system", value: "Android R" },
      { label: "Wi‑Fi", value: "Yes" },
      { label: "HDMI", value: "3 ports" },
      { label: "USB", value: "2 ports" },
      { label: "Dimensions (approx., with stand)", value: "1295 × 750 × 80 mm" },
      { label: "Audio", value: "Dolby Digital Plus 10W × 2" },
      { label: "Color", value: "BLACK" },
      { label: "Warranty", value: "1 year" },
    ],
    longIntro:
      "The Hyundai HYLED-58UHD7A combines advanced technology with stunning 4K UHD resolution so you can enjoy every detail. Perfect for your home, it features Wi‑Fi connectivity, an Android operating system, and excellent color reproduction for an immersive viewing experience.",
    manualFileLabel: "Download PDF (2.3 MB)",
  },
  "tv-43-full-hd": {
    sku: "HYLED-43FHD7A",
    grid: [
      { label: "Brand", value: "HYUNDAI" },
      { label: "Model", value: "HYLED-43FHD7A" },
      { label: "Screen size", value: '43"' },
      { label: "Resolution", value: "Full HD 1920 × 1080" },
      { label: "Operating system", value: "Android R" },
      { label: "Wi‑Fi", value: "Yes" },
      { label: "HDMI", value: "As marked on unit" },
      { label: "USB", value: "As marked on unit" },
      { label: "Dimensions (approx.)", value: "970 × 565 × 74 mm" },
      { label: "Audio", value: "Dolby Digital Plus 8W × 2" },
      { label: "Color", value: "BLACK" },
      { label: "Warranty", value: "1 year" },
    ],
    list: [
      { label: "Brand", value: "HYUNDAI" },
      { label: "Model", value: "HYLED-43FHD7A" },
      { label: "Screen size", value: '43"' },
      { label: "Resolution", value: "Full HD 1920 × 1080" },
      { label: "Operating system", value: "Android R" },
      { label: "Wi‑Fi", value: "Yes" },
      { label: "HDMI", value: "As marked on unit" },
      { label: "USB", value: "As marked on unit" },
      { label: "Dimensions (approx.)", value: "970 × 565 × 74 mm" },
      { label: "Audio", value: "Dolby Digital Plus 8W × 2" },
      { label: "Color", value: "BLACK" },
      { label: "Warranty", value: "1 year" },
    ],
    longIntro:
      "The Hyundai HYLED-43FHD7A combines advanced technology with stunning resolution so you can enjoy every detail. Perfect for your home, it features Wi‑Fi connectivity, an Android operating system, and excellent color reproduction for an immersive viewing experience.",
    manualFileLabel: "Download PDF (2.0 MB)",
  },
  "tv-32-hd": {
    sku: "HYLED-32HD7A",
    grid: [
      { label: "Brand", value: "HYUNDAI" },
      { label: "Model", value: "HYLED-32HD7A" },
      { label: "Screen size", value: '32"' },
      { label: "Resolution", value: "HD" },
      { label: "Operating system", value: "Android R" },
      { label: "Wi‑Fi", value: "Yes" },
      { label: "Dimensions (with stand)", value: "800 × 520 × 128 mm" },
      { label: "Weight (net / gross)", value: "3500 g / 4950 g" },
      { label: "Warranty", value: "1 year" },
      { label: "Color", value: "BLACK" },
      { label: "Speakers", value: "Integrated speaker" },
      { label: "Voice control", value: "No" },
    ],
    list: [
      { label: "Brand", value: "HYUNDAI" },
      { label: "Model", value: "HYLED-32HD7A" },
      { label: "Screen size", value: '32"' },
      { label: "Resolution", value: "HD" },
      { label: "Operating system", value: "Android R" },
      { label: "Wi‑Fi", value: "Yes" },
      { label: "Dimensions (with stand)", value: "800 × 520 × 128 mm" },
      { label: "Weight (net / gross)", value: "3500 g / 4950 g" },
      { label: "Warranty", value: "1 year" },
      { label: "Color", value: "BLACK" },
      { label: "Speakers", value: "Integrated speaker" },
      { label: "Voice control", value: "No" },
    ],
    longIntro:
      "The Hyundai HYLED-32HD7A TV combines advanced technology with stunning resolution so you can enjoy every detail. Perfect for your home, it features Wi‑Fi connectivity, an Android operating system, and excellent color reproduction for an immersive viewing experience.",
    manualFileLabel: "Download PDF (1.6 MB)",
  },
  "ac-1-5-ton-inverter": {
    sku: "HY10INV-3200FC",
    grid: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY10INV-3200FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "3224 W · 2772.64 kcal/h" },
      { label: "Technology", value: "Inverter" },
      { label: "Energy efficiency", value: "A+" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R410A" },
      { label: "Outdoor unit (W×D×H)", value: "818 × 325 × 520 mm" },
      { label: "Indoor unit (W×H×D)", value: "777 × 250 × 201 mm" },
      { label: "Outdoor / indoor weight", value: "8.0 kg / 10.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "52 dB / 33–39 dB" },
      { label: "Nominal heat power", value: "940 W (max 1350 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    list: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY10INV-3200FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "3224 W · 2772.64 kcal/h" },
      { label: "Technology", value: "Inverter" },
      { label: "Energy efficiency", value: "A+" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R410A" },
      { label: "Outdoor unit (W×D×H)", value: "818 × 325 × 520 mm" },
      { label: "Indoor unit (W×H×D)", value: "777 × 250 × 201 mm" },
      { label: "Outdoor / indoor weight", value: "8.0 kg / 10.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "52 dB / 33–39 dB" },
      { label: "Nominal heat power", value: "940 W (max 1350 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    longIntro:
      "Discover uninterrupted comfort with the HYUNDAI Inverter air conditioner at 3224 kilocalories per hour. Its advanced Inverter technology adjusts energy use to your temperature needs, delivering optimal performance and a significant reduction in electricity use. Ideal for small or medium spaces, it offers cooling in summer and heating in winter with quiet, stable operation — in a modern white design made to blend into your home.",
    manualFileLabel: "Download PDF (1.9 MB)",
  },
  "ac-3224-on-off": {
    sku: "HY9-3200FC",
    grid: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY9-3200FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "3224 W · 2772.64 kcal/h" },
      { label: "Technology", value: "On-Off" },
      { label: "Energy efficiency", value: "A" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R410A" },
      { label: "Outdoor unit (W×D×H)", value: "818 × 325 × 520 mm" },
      { label: "Indoor unit (W×H×D)", value: "777 × 250 × 201 mm" },
      { label: "Outdoor / indoor weight", value: "20.0 kg / 10.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "52 dB / 33–42 dB" },
      { label: "Nominal heat power", value: "998 W (max 1298 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    list: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY9-3200FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "3224 W · 2772.64 kcal/h" },
      { label: "Technology", value: "On-Off" },
      { label: "Energy efficiency", value: "A" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R410A" },
      { label: "Outdoor unit (W×D×H)", value: "818 × 325 × 520 mm" },
      { label: "Indoor unit (W×H×D)", value: "777 × 250 × 201 mm" },
      { label: "Outdoor / indoor weight", value: "20.0 kg / 10.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "52 dB / 33–42 dB" },
      { label: "Nominal heat power", value: "998 W (max 1298 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    longIntro:
      "Enjoy the perfect climate in your home with the HYUNDAI On-Off 3224 W air conditioner. This unit offers excellent cooling and heating capacity, ideal for maintaining comfort in medium-sized rooms. Its simple, reliable operation lets you control the temperature efficiently, while a compact, modern white design fits seamlessly into any space. On-Off technology keeps operation straightforward when you need steady performance without complexity.",
    manualFileLabel: "Download PDF (1.9 MB)",
  },
  "ac-5275-on-off": {
    sku: "HY9-5000FC",
    grid: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY9-5000FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "5275 W · 4536.5 kcal/h" },
      { label: "Technology", value: "On-Off" },
      { label: "Energy efficiency", value: "A" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R410A" },
      { label: "Outdoor unit (W×D×H)", value: "853 × 349 × 602 mm" },
      { label: "Indoor unit (W×H×D)", value: "910 × 294 × 206 mm" },
      { label: "Outdoor / indoor weight", value: "25.0 kg / 13.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "56 dB / 41–50 dB" },
      { label: "Nominal heat power", value: "1525 W (max 1983 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    list: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY9-5000FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "5275 W · 4536.5 kcal/h" },
      { label: "Technology", value: "On-Off" },
      { label: "Energy efficiency", value: "A" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R410A" },
      { label: "Outdoor unit (W×D×H)", value: "853 × 349 × 602 mm" },
      { label: "Indoor unit (W×H×D)", value: "910 × 294 × 206 mm" },
      { label: "Outdoor / indoor weight", value: "25.0 kg / 13.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "56 dB / 41–50 dB" },
      { label: "Nominal heat power", value: "1525 W (max 1983 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    longIntro:
      "For spaces requiring greater cooling capacity, the HYUNDAI On-Off air conditioner at 5275 W is a strong choice. Its heating and cooling system helps maintain a comfortable environment year-round, while On-Off technology keeps temperature control simple and effective. A robust, stylish white cabinet suits demanding installs and adds a clean look to living spaces and workplaces alike — powerful performance without fuss.",
    manualFileLabel: "Download PDF (2.2 MB)",
  },
  "ac-6540-on-off": {
    sku: "HY8-6000FC",
    grid: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY8-6000FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "6540 W · 5624.4 kcal/h" },
      { label: "Technology", value: "On-Off" },
      { label: "Energy efficiency", value: "A" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R410A" },
      { label: "Outdoor unit (W×D×H)", value: "820 × 300 × 605 mm" },
      { label: "Indoor unit (W×H×D)", value: "1010 × 315 × 220 mm" },
      { label: "Outdoor / indoor weight", value: "13.0 kg / 16.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "58 dB / 43–51 dB" },
      { label: "Nominal heat power", value: "1861 W (max 2140 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    list: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY8-6000FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "6540 W · 5624.4 kcal/h" },
      { label: "Technology", value: "On-Off" },
      { label: "Energy efficiency", value: "A" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R410A" },
      { label: "Outdoor unit (W×D×H)", value: "820 × 300 × 605 mm" },
      { label: "Indoor unit (W×H×D)", value: "1010 × 315 × 220 mm" },
      { label: "Outdoor / indoor weight", value: "13.0 kg / 16.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "58 dB / 43–51 dB" },
      { label: "Nominal heat power", value: "1861 W (max 2140 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    longIntro:
      "The HYUNDAI On-Off air conditioner at 6540 W offers powerful performance to keep your home comfortable year-round. With On-Off technology, this unit delivers straightforward temperature control for cooling on hot days and heating in winter. Its elegant white design blends into most décors, while an efficient system helps you manage energy use without giving up comfort.",
    manualFileLabel: "Download PDF (2.5 MB)",
  },
  "ac-1-ton-inverter": {
    sku: "HY11INV-3200FC",
    grid: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY11INV-3200FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "3200 W (2752 BTU/h)" },
      { label: "Technology", value: "Inverter" },
      { label: "Energy efficiency", value: "A++" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R32" },
      { label: "Outdoor unit (W×D×H)", value: "765 × 310 × 481 mm" },
      { label: "Indoor unit (W×H×D)", value: "777 × 250 × 201 mm" },
      { label: "Outdoor / indoor weight", value: "7.5 kg / 10.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "53 dB / 33–39 dB" },
      { label: "Nominal heat power", value: "975 W (max 1400 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    list: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY11INV-3200FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "3200 W (2752 BTU/h)" },
      { label: "Technology", value: "Inverter" },
      { label: "Energy efficiency", value: "A++" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R32" },
      { label: "Outdoor unit (W×D×H)", value: "765 × 310 × 481 mm" },
      { label: "Indoor unit (W×H×D)", value: "777 × 250 × 201 mm" },
      { label: "Outdoor / indoor weight", value: "7.5 kg / 10.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "53 dB / 33–39 dB" },
      { label: "Nominal heat power", value: "975 W (max 1400 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    longIntro:
      "Small but powerful. The HYUNDAI Inverter air conditioner with 3200 BTU/h delivers superior performance in a compact format, ideal for small to medium-sized rooms. Thanks to Inverter technology, this unit automatically adjusts energy consumption, allowing you to enjoy significant savings without sacrificing comfort. Cool in summer, warm in winter, and energy efficiency that cares for both your home and the environment.",
    manualFileLabel: "Download PDF (1.7 MB)",
  },
  "ac-2-ton-inverter": {
    sku: "HY10INV-5000FC",
    grid: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY10INV-5000FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "5000 W · 4300 kcal/h" },
      { label: "Technology", value: "Inverter" },
      { label: "Energy efficiency", value: "A++" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R410A" },
      { label: "Outdoor unit (W×D×H)", value: "853 × 349 × 602 mm" },
      { label: "Indoor unit (W×H×D)", value: "910 × 294 × 206 mm" },
      { label: "Outdoor / indoor weight", value: "35.0 kg / 10.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "56 dB / 39–45 dB" },
      { label: "Nominal heat power", value: "1588 W (max 2550 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    list: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY10INV-5000FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "5000 W · 4300 kcal/h" },
      { label: "Technology", value: "Inverter" },
      { label: "Energy efficiency", value: "A++" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R410A" },
      { label: "Outdoor unit (W×D×H)", value: "853 × 349 × 602 mm" },
      { label: "Indoor unit (W×H×D)", value: "910 × 294 × 206 mm" },
      { label: "Outdoor / indoor weight", value: "35.0 kg / 10.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "56 dB / 39–45 dB" },
      { label: "Nominal heat power", value: "1588 W (max 2550 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    longIntro:
      "If you need a powerful, efficient air conditioner, the HYUNDAI Inverter at 5000 kilocalories per hour is the right choice. Built for large rooms, it delivers precise, steady comfort all year. Inverter technology optimizes energy use and helps extend the life of the unit — comfortable on hot days and cold days alike, in a reliable, modern, lower-impact package.",
    manualFileLabel: "Download PDF (2.2 MB)",
  },
  "ac-5000-hy11": {
    sku: "HY11INV-5000FC",
    grid: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY11INV-5000FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "5000 W · 4300 kcal/h" },
      { label: "Technology", value: "Inverter" },
      { label: "Energy efficiency", value: "A++" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R32" },
      { label: "Outdoor unit (W×D×H)", value: "853 × 349 × 602 mm" },
      { label: "Indoor unit (W×H×D)", value: "910 × 294 × 206 mm" },
      { label: "Outdoor / indoor weight", value: "33.0 kg / 13.5 kg" },
      { label: "Noise (outdoor / indoor)", value: "55 dB / 32–44 dB" },
      { label: "Nominal heat power", value: "1460 W (max 2500 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    list: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY11INV-5000FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "5000 W · 4300 kcal/h" },
      { label: "Technology", value: "Inverter" },
      { label: "Energy efficiency", value: "A++" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R32" },
      { label: "Outdoor unit (W×D×H)", value: "853 × 349 × 602 mm" },
      { label: "Indoor unit (W×H×D)", value: "910 × 294 × 206 mm" },
      { label: "Outdoor / indoor weight", value: "33.0 kg / 13.5 kg" },
      { label: "Noise (outdoor / indoor)", value: "55 dB / 32–44 dB" },
      { label: "Nominal heat power", value: "1460 W (max 2500 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    longIntro:
      "The HYUNDAI Inverter at 5000 kilocalories per hour combines next-generation efficiency with real comfort for large rooms. It adapts output to your heating and cooling needs while trimming energy use, offers cold in summer and heat in winter, and pairs a clean white design with dependable inverter performance and R32 refrigerant.",
    manualFileLabel: "Download PDF (2.2 MB)",
  },
  "ac-5000-wifi": {
    sku: "HY11INV-5000FCW",
    grid: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY11INV-5000FCW" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "5000 W · 4300 kcal/h" },
      { label: "Technology", value: "Inverter · Wi‑Fi" },
      { label: "Energy efficiency", value: "A++" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R32" },
      { label: "Outdoor unit (W×D×H)", value: "853 × 349 × 602 mm" },
      { label: "Indoor unit (W×H×D)", value: "910 × 294 × 206 mm" },
      { label: "Outdoor / indoor weight", value: "27.0 kg / 13.5 kg" },
      { label: "Noise (outdoor / indoor)", value: "55 dB / 32–44 dB" },
      { label: "Nominal heat power", value: "1460 W (max 2500 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    list: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY11INV-5000FCW" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "5000 W · 4300 kcal/h" },
      { label: "Technology", value: "Inverter · Wi‑Fi" },
      { label: "Energy efficiency", value: "A++" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R32" },
      { label: "Outdoor unit (W×D×H)", value: "853 × 349 × 602 mm" },
      { label: "Indoor unit (W×H×D)", value: "910 × 294 × 206 mm" },
      { label: "Outdoor / indoor weight", value: "27.0 kg / 13.5 kg" },
      { label: "Noise (outdoor / indoor)", value: "55 dB / 32–44 dB" },
      { label: "Nominal heat power", value: "1460 W (max 2500 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    longIntro:
      "The HYUNDAI Inverter HY11INV-5000FCW air conditioner is synonymous with comfort and innovation. Its Inverter technology enables more efficient operation, adjusting power to the target temperature and helping avoid energy spikes — optimizing performance and supporting long service life. Wi‑Fi connectivity lets you control the unit from your smartphone from anywhere, scheduling on and off to match your routine. An air filtration path helps capture impurities and improve indoor air quality. With a sleek, quiet presence, the HY11INV-5000FCW suits anyone who wants powerful, efficient, easy-to-use climate control.",
    manualFileLabel: "Download PDF (2.2 MB)",
  },
  "ac-6400-inverter": {
    sku: "HY10INV-6000FC",
    grid: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY10INV-6000FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "6400 W · 5504 kcal/h" },
      { label: "Technology", value: "Inverter" },
      { label: "Energy efficiency", value: "A++" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R410A" },
      { label: "Outdoor unit (W×D×H)", value: "853 × 349 × 602 mm" },
      { label: "Indoor unit (W×H×D)", value: "1010 × 315 × 220 mm" },
      { label: "Outdoor / indoor weight", value: "33.0 kg / 16.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "56 dB / 44–50 dB" },
      { label: "Nominal heat power", value: "1874 W (max 2600 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    list: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY10INV-6000FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "6400 W · 5504 kcal/h" },
      { label: "Technology", value: "Inverter" },
      { label: "Energy efficiency", value: "A++" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R410A" },
      { label: "Outdoor unit (W×D×H)", value: "853 × 349 × 602 mm" },
      { label: "Indoor unit (W×H×D)", value: "1010 × 315 × 220 mm" },
      { label: "Outdoor / indoor weight", value: "33.0 kg / 16.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "56 dB / 44–50 dB" },
      { label: "Nominal heat power", value: "1874 W (max 2600 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    longIntro:
      "Maximum power and efficiency in a single unit. The HYUNDAI Inverter air conditioner at 6400 W is the ultimate solution for those seeking superior performance. With Inverter technology, it automatically adjusts energy consumption to maintain the perfect temperature in both cooling and heating modes. This model is ideal for large spaces requiring precise, constant temperature control — and its sophisticated white design adds distinction to any room.",
    manualFileLabel: "Download PDF (2.5 MB)",
  },
  "ac-6400-hy11": {
    sku: "HY11INV-6000FC",
    grid: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY11INV-6000FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "6400 W · 5504 kcal/h" },
      { label: "Technology", value: "Inverter" },
      { label: "Energy efficiency", value: "A++" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R32" },
      { label: "Outdoor unit (W×D×H)", value: "853 × 349 × 602 mm" },
      { label: "Indoor unit (W×H×D)", value: "1010 × 315 × 220 mm" },
      { label: "Outdoor / indoor weight", value: "33.0 kg / 16.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "55 dB / 32–47 dB" },
      { label: "Nominal heat power", value: "1959 W (max 2600 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    list: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY11INV-6000FC" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "6400 W · 5504 kcal/h" },
      { label: "Technology", value: "Inverter" },
      { label: "Energy efficiency", value: "A++" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R32" },
      { label: "Outdoor unit (W×D×H)", value: "853 × 349 × 602 mm" },
      { label: "Indoor unit (W×H×D)", value: "1010 × 315 × 220 mm" },
      { label: "Outdoor / indoor weight", value: "33.0 kg / 16.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "55 dB / 32–47 dB" },
      { label: "Nominal heat power", value: "1959 W (max 2600 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    longIntro:
      "Designed for large spaces, the HYUNDAI Inverter air conditioner at 6400 W guarantees optimal climate control at all times. Its Inverter technology regulates energy consumption according to temperature conditions, offering consistent and efficient performance. Quiet operation and a minimalist white design make it an excellent choice for both homes and workplaces that require a comfortable, controlled environment.",
    manualFileLabel: "Download PDF (2.5 MB)",
  },
  "ac-6000-wifi": {
    sku: "HY11INV-6000FCW",
    grid: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY11INV-6000FCW" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "6400 W · 5504 kcal/h" },
      { label: "Technology", value: "Inverter · Wi‑Fi" },
      { label: "Energy efficiency", value: "A++" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R32" },
      { label: "Outdoor unit (W×D×H)", value: "853 × 349 × 602 mm" },
      { label: "Indoor unit (W×H×D)", value: "1010 × 315 × 220 mm" },
      { label: "Outdoor / indoor weight", value: "32.0 kg / 13.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "55 dB / 32–47 dB" },
      { label: "Nominal heat power", value: "1959 W (max 2600 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    list: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY11INV-6000FCW" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "6400 W · 5504 kcal/h" },
      { label: "Technology", value: "Inverter · Wi‑Fi" },
      { label: "Energy efficiency", value: "A++" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R32" },
      { label: "Outdoor unit (W×D×H)", value: "853 × 349 × 602 mm" },
      { label: "Indoor unit (W×H×D)", value: "1010 × 315 × 220 mm" },
      { label: "Outdoor / indoor weight", value: "32.0 kg / 13.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "55 dB / 32–47 dB" },
      { label: "Nominal heat power", value: "1959 W (max 2600 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    longIntro:
      "The HYUNDAI Inverter HY11INV-6000FCW air conditioner is the perfect combination of technology, efficiency, and comfort. Designed for optimal performance, its Inverter system automatically adjusts compressor speed and can reduce energy use by up to 40% compared to many conventional non-inverter units. Integrated Wi‑Fi lets you control functions from your smartphone so comfort is ready when you arrive. An advanced filtration path helps capture dust and allergens, while a modern white finish suits homes and offices alike. With the HYUNDAI HY11INV-6000FCW, enjoy steady climate control year-round.",
    manualFileLabel: "Download PDF (2.5 MB)",
  },
  "ac-3200-wifi": {
    sku: "HY11INV-3200FCW",
    grid: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY11INV-3200FCW" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "3200 W · 2752 kcal/h" },
      { label: "Technology", value: "Inverter · Wi‑Fi" },
      { label: "Energy efficiency", value: "A++" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R32" },
      { label: "Outdoor unit (W×D×H)", value: "795 × 305 × 549 mm" },
      { label: "Indoor unit (W×H×D)", value: "979 × 372 × 277 mm" },
      { label: "Outdoor / indoor weight", value: "23.0 kg / 10.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "55 dB / 32–44 dB" },
      { label: "Nominal heat power", value: "1460 W (max 2500 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    list: [
      { label: "Brand", value: "Hyundai Electronics" },
      { label: "Model", value: "HY11INV-3200FCW" },
      { label: "Color", value: "White" },
      { label: "Operating modes", value: "Cooling / Heating" },
      { label: "Cooling capacity", value: "3200 W · 2752 kcal/h" },
      { label: "Technology", value: "Inverter · Wi‑Fi" },
      { label: "Energy efficiency", value: "A++" },
      { label: "Voltage", value: "220V" },
      { label: "Refrigerant", value: "R32" },
      { label: "Outdoor unit (W×D×H)", value: "795 × 305 × 549 mm" },
      { label: "Indoor unit (W×H×D)", value: "979 × 372 × 277 mm" },
      { label: "Outdoor / indoor weight", value: "23.0 kg / 10.0 kg" },
      { label: "Noise (outdoor / indoor)", value: "55 dB / 32–44 dB" },
      { label: "Nominal heat power", value: "1460 W (max 2500 W)" },
      { label: "Warranty", value: "1 year" },
    ],
    longIntro:
      "If you are looking for an efficient, high-tech air conditioner, the HYUNDAI Inverter HY11INV-3200FCW is the ideal choice. Its Inverter technology automatically adjusts compressor speed to maintain a stable temperature, reducing energy use and avoiding sudden swings. With built-in Wi‑Fi, you can power the unit on or off and change the temperature from your phone for comfort even when you are away. A capable filtration path helps improve air quality by capturing dust and allergens. Quiet operation and a modern white design make it easy to live with every day.",
    manualFileLabel: "Download PDF (1.8 MB)",
  },
};

export function getProductDetailExtra(productId: string): ProductDetailExtra {
  return (
    productDetailExtras[productId] ?? {
      sku: "HY-DEMO-001",
      grid: [
        { label: "Brand", value: "HYUNDAI" },
        { label: "Category", value: "Electronics" },
        { label: "Model", value: productId.toUpperCase() },
        { label: "Warranty", value: "1 Year" },
        { label: "Support", value: "Authorized service" },
        { label: "Region", value: "Global demo" },
        { label: "Dimensions", value: "—" },
        { label: "Weight", value: "—" },
        { label: "Package", value: "Standard retail box" },
      ],
      list: [
        { label: "Brand", value: "HYUNDAI" },
        { label: "Category", value: "Electronics" },
        { label: "Model", value: productId.toUpperCase() },
        { label: "Warranty", value: "1 Year" },
        { label: "Support", value: "Authorized service" },
        { label: "Region", value: "Global demo" },
        { label: "Dimensions", value: "—" },
        { label: "Weight", value: "—" },
        { label: "Package", value: "Standard retail box" },
      ],
      longIntro:
        "HYUNDAI Electronics products are engineered for dependable everyday performance. Refer to the manual for installation guidance and safety information.",
      manualFileLabel: "Download PDF (1.0 MB)",
    }
  );
}
